using System.IO.Pipes;
using System.Net;
using System.Net.Sockets;
using System.Text.Json;
using Microsoft.AspNetCore.DataProtection;
using MQTTnet;
using MQTTnet.Server;
using RTSPView.Controller;
using RTSPView.Core;
using RTSPView.Infrastructure;
var directory=Path.Combine(Path.GetTempPath(),"RTSPView-issue13-"+Guid.NewGuid().ToString("N")); Directory.CreateDirectory(directory);
var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();var port=((IPEndPoint)listener.LocalEndpoint).Port;listener.Stop();
using var broker=new MqttFactory().CreateMqttServer(new MqttServerOptionsBuilder().WithDefaultEndpoint().WithDefaultEndpointBoundIPAddress(IPAddress.Loopback).WithDefaultEndpointPort(port).Build());await broker.StartAsync();
var store=new JsonSettingsStore(Path.Combine(directory,"settings.json"));var settings=new AppSettings().Normalize();
await store.SaveAsync(settings with {Cameras=settings.Cameras.Select(c=>c.Slot==1?c with {Enabled=true,RtspUrl="rtsp://example.test/fixture"}:c).ToArray()});
var name="RTSPView-issue13-"+Guid.NewGuid().ToString("N");var client=new ViewerCommandClient(name);
using var service=new AutomationService(directory,DataProtectionProvider.Create(new DirectoryInfo(Path.Combine(directory,"keys"))),client);
var rule=new AutomationRule {Name="Fixture",Action=AutomationAction.FullScreen,CameraSlot=1,Sources=[new(1,"fixture/person")]};
await service.SaveAsync(new(new AutomationSettings {Enabled=true,Host="127.0.0.1",Port=port,Rules=[rule]},null),default);
await service.StartAsync(default);
for(var i=0;i<100 && (service.Status.Connection!="Connected" || service.Status.Delivery?.Success!=false);i++)await Task.Delay(100);
await Task.Delay(1600);
Console.WriteLine("Initial: "+JsonSerializer.Serialize(new {service.Status.Connection,service.Status.Delivery}));
using var cancel=new CancellationTokenSource();
var received = new System.Collections.Concurrent.ConcurrentQueue<ViewerCommand>();
var server=Task.Run(async()=>{try {while(!cancel.IsCancellationRequested){await using var pipe=new NamedPipeServerStream(name,PipeDirection.InOut,1,PipeTransmissionMode.Byte,PipeOptions.Asynchronous|PipeOptions.CurrentUserOnly);await pipe.WaitForConnectionAsync(cancel.Token);using var reader=new StreamReader(pipe,leaveOpen:true);await using var writer=new StreamWriter(pipe,leaveOpen:true){AutoFlush=true};var command=JsonSerializer.Deserialize<ViewerCommand>((await reader.ReadLineAsync(cancel.Token))!)!;received.Enqueue(command);await writer.WriteLineAsync(JsonSerializer.Serialize(new ViewerCommandResult(command.Id,true,"Fixture acknowledged")));}}catch(OperationCanceledException){}});
var healthy=await client.SendAsync(ViewerCommandType.EnterFullScreen,null,default);if(!healthy.Success)throw new Exception("Healthy fixture command failed");
for(var i=0;i<100 && service.Status.ViewerConnection?.Success!=true;i++)await Task.Delay(100);
if(service.Status.ViewerConnection?.Success!=true)throw new Exception("Viewer recovery was not detected");
if(received.Any(c=>c.Type==ViewerCommandType.AutomationOverlays))throw new Exception("Health probe replayed automation");
Console.WriteLine("Recovered status: "+JsonSerializer.Serialize(new {service.Status.Connection,service.Status.Delivery,service.Status.ViewerConnection}));
if(service.Status.Delivery?.Success!=false)throw new Exception("Expected stale failure was not reproduced");
var test=await service.TestRuleAsync(rule.Id,1,default);if(!test.Success)throw new Exception("Automation test failed");
Console.WriteLine("After fresh rule test: "+JsonSerializer.Serialize(new {service.Status.Connection,service.Status.Delivery}));
await service.StopAsync(default);cancel.Cancel();await server;await broker.StopAsync();
Console.WriteLine("PASS Viewer health recovers without replaying automation; failed delivery history retained; fresh rule test succeeds.");
