// Real HTTP integration checks against an isolated Controller and data directory.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict'),net=require('node:net');
(async()=>{
 const root=path.resolve(__dirname,'..'),data=path.join(root,'artifacts','security','http-'+crypto.randomUUID());fs.mkdirSync(data,{recursive:true});
 const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p))})});
 const dotnet=process.env.DOTNET_HOST_PATH||path.join(root,'.toolchain','dotnet','dotnet.exe');
 const child=cp.spawn(dotnet,[path.join(root,'src/RTSPView.Controller/bin/Release/net8.0-windows/win-x64/SpotMonitor.Controller.dll')],{cwd:root,windowsHide:true,env:{...process.env,DOTNET_ROOT:path.dirname(dotnet),ASPNETCORE_ENVIRONMENT:'Testing',ASPNETCORE_URLS:'http://127.0.0.1:'+port,RTSPVIEW_DATA_DIR:data},stdio:'ignore'});
 const client=()=>({cookies:new Map(),csrf:''});const a=client(),b=client();
 async function request(c,url,method='GET',body){const r=await fetch('http://127.0.0.1:'+port+url,{method,headers:{Cookie:[...c.cookies].map(([k,v])=>k+'='+v).join('; '),'Content-Type':'application/json','X-CSRF-Token':c.csrf},body:body===undefined?undefined:JSON.stringify(body)});for(const cookie of r.headers.getSetCookie()){const pair=cookie.split(';')[0],i=pair.indexOf('=');c.cookies.set(pair.slice(0,i),pair.slice(i+1));}const text=await r.text();let json;try{json=JSON.parse(text)}catch{}return{status:r.status,json,text};}
 const session=async c=>{const r=await request(c,'/api/session');c.csrf=r.json.csrfToken;return r.json};
 try{
  let ready=false;for(let i=0;i<100;i++){try{await session(a);ready=true;break}catch{await new Promise(r=>setTimeout(r,100))}}assert(ready,'Controller starts');
  const hostileHostStatus=await new Promise((resolve,reject)=>{require('node:http').get({hostname:'127.0.0.1',port,path:'/api/session',headers:{Host:'untrusted.example'}},r=>{r.resume();resolve(r.statusCode)}).on('error',reject)});
  assert.equal(hostileHostStatus,400,'untrusted host rejected');
  const program=fs.readFileSync(path.join(root,'src/RTSPView.Controller/Program.cs'),'utf8');
  const routes=[...program.matchAll(/app\.Map(Get|Post|Put|Delete)\("([^"\n]+)"/g)].map(m=>[m[1].toUpperCase(),m[2].replace(/\{slot:int\}/g,'1')]).filter(([,p])=>!['/api/session','/api/auth/login'].includes(p));
  routes.push(['GET','/api/weather'],['GET','/api/weather/search?q=Seattle'],['PUT','/api/weather/overlays/1']);
  for(const[method,url]of routes)assert.equal((await request(a,url,method,method==='GET'?undefined:{})).status,401,'anonymous blocked: '+url);
  assert.equal((await request(a,'/api/auth/login','POST',{password:'admin'})).json.passwordChangeRequired,true);
  assert.equal((await session(a)).passwordChangeRequired,true);
  for(const[method,url]of routes.filter(([,p])=>!['/api/auth/password','/api/auth/logout'].includes(p)))assert.equal((await request(a,url,method,method==='GET'?undefined:{})).status,403,'setup gate: '+url);
  await session(b);assert.equal((await request(b,'/api/auth/login','POST',{password:'admin'})).status,200);
  for(const [newPassword,message] of [['   ','Enter a new password; it cannot be blank.'],['x'.repeat(1025),'The new password must be 1024 characters or fewer.'],['admin','The new password cannot be the initial password admin.']]) {
   const rejected=await request(a,'/api/auth/password','POST',{currentPassword:'admin',newPassword});assert.equal(rejected.status,400);assert.equal(rejected.json.error,message);
  }
  const password='t-'+crypto.randomUUID().slice(0,4); // A short password must complete setup successfully.
  assert.equal((await request(a,'/api/auth/password','POST',{currentPassword:'admin',newPassword:password})).status,200);
  assert.equal((await request(b,'/api/config')).status,401,'other session invalidated');
  assert.equal((await request(a,'/api/auth/login','POST',{password:'admin'})).status,401,'default revoked');
  assert.equal((await request(a,'/api/auth/login','POST',{password})).status,200);
  assert.equal((await session(a)).passwordChangeRequired,false);
  const same=await request(a,'/api/auth/password','POST',{currentPassword:password,newPassword:password});assert.equal(same.status,400);assert.equal(same.json.error,'The new password must differ from your current password.');
  const wrong=await request(a,'/api/auth/password','POST',{currentPassword:'wrong-current',newPassword:'another'});assert.equal(wrong.status,400);assert.equal(wrong.json.error,'Current password is incorrect.');
  assert.equal((await request(a,'/api/control/application/restart','POST',{confirmed:false})).status,400,'restart needs explicit confirmation');
  assert.equal((await request(a,'/api/control/application/restart','POST',{confirmed:true})).status,409,'test host cannot restart real processes');
  const instance=(await request(a,'/api/control/application/status')).json.instance;
  assert.equal(typeof instance,'string');
  const savedCsrf=a.csrf;a.csrf='';
  assert.equal((await request(a,'/api/control/application/restart','POST',{confirmed:true})).status,400,'restart requires CSRF');a.csrf=savedCsrf;
  const config=(await request(a,'/api/config')).json;assert(config,'configuration loads');
  const directTest=await request(a,'/api/streams/test','POST',{rtspUrl:'https://media.example/live.m3u8'});
  assert.equal(directTest.status,200);assert.match(directTest.json.message,/URL accepted/);
  assert.equal((await request(a,'/api/streams/test','POST',{rtspUrl:'file:///C:/private.txt'})).status,400);
  const streamCsrf=a.csrf;a.csrf='';
  assert.equal((await request(a,'/api/streams/test','POST',{rtspUrl:'https://media.example/live.m3u8'})).status,400);a.csrf=streamCsrf;
  if(fs.existsSync(path.join(root,'src/RTSPView.Controller/bin/Release/net8.0-windows/win-x64/Streaming/stream-resolver.exe'))){
    const media=Buffer.from('isolated media fixture'.repeat(100));
    const origin=require('node:http').createServer((req,res)=>{const page=req.url==='/watch';res.setHeader('Content-Type',page?'text/html':'video/mp4');res.end(page?'<html><head><title>Fixture</title></head><body><video src="/fixture.mp4"></video></body></html>':media);});
    await new Promise(resolve=>origin.listen(0,'127.0.0.1',resolve));
    try{const result=await request(a,'/api/streams/test','POST',{rtspUrl:'http://127.0.0.1:'+origin.address().port+'/watch',sourceMode:3,maximumHeight:720});assert.equal(result.status,200,JSON.stringify(result.json));assert.match(result.json.message,/yt-dlp.*received media/);}
    finally{await new Promise(resolve=>origin.close(resolve));}
  }
  const website={...config.cameras[0],rtspUrl:'https://site.example/watch?v=fixture',sourceMode:3,maximumHeight:1080};
  assert.equal((await request(a,'/api/cameras/1','PUT',website)).status,200);
  const websiteSaved=(await request(a,'/api/config')).json.cameras[0];assert.equal(websiteSaved.sourceMode,3);assert.equal(websiteSaved.maximumHeight,1080);
  assert.equal((await request(a,'/api/cameras/1','PUT',config.cameras[0])).status,200);
  const weather={location:'Seattle',latitude:47.6062,longitude:-122.3321,preset:'compact',units:'imperial',fields:['temperature','condition','highLow']};
  const weatherOverlay={hostCameraSlot:1,enabled:true,weather,widthPercent:40,x:0,y:100,margin:12};
  assert.equal((await request(a,'/api/weather/overlays/1','PUT',weatherOverlay)).status,200,'weather overlay saves');
  const withWeather=(await request(a,'/api/config')).json;
  assert.equal(withWeather.weatherOverlays[0].weather.location,'Seattle','weather location persists');
  assert.deepEqual(withWeather.cameras,config.cameras,'weather save preserves camera connections');
  assert.equal((await request(a,'/api/weather/overlays/1','PUT',{...weatherOverlay,weather:{...weather,latitude:91}})).status,400,'invalid weather location rejected');
  const weatherLayouts=config.layouts.map((l,i)=>i===0?{...l,tiles:l.tiles.map((t,j)=>j===8?{...t,kind:'weather',cameraSlot:0,itemId:'weather-1',weather}:t)}:l);
  assert.equal((await request(a,'/api/layouts','PUT',{layouts:weatherLayouts,activeLayoutId:config.activeLayoutId})).status,200,'mixed weather layout saves');
  assert.equal((await request(a,'/api/config')).json.layouts[0].tiles[8].kind,'weather','weather tile survives reload');
  const weatherCsrf=a.csrf;a.csrf='';assert.equal((await request(a,'/api/weather/overlays/1','PUT',weatherOverlay)).status,400,'weather mutations require CSRF');a.csrf=weatherCsrf;
  assert.equal((await request(a,'/api/layouts','PUT',{layouts:config.layouts,activeLayoutId:config.activeLayoutId})).status,200,'restore camera layout after weather checks');
  const appearanceLayouts=config.layouts.map(l=>({...l,borderColor:'#ff0000',backgroundColor:'#123456',showTileBorders:false}));
  const appearanceSave=await request(a,'/api/layouts','PUT',{layouts:appearanceLayouts,activeLayoutId:config.activeLayoutId});
  assert.equal(appearanceSave.status,200,'real layout appearance API saves: '+appearanceSave.text);
  assert.deepEqual((await request(a,'/api/config')).json.layouts,appearanceLayouts,'layout appearance survives API reload');
  assert.equal((await request(a,'/api/layouts','PUT',{layouts:config.layouts,activeLayoutId:config.activeLayoutId})).status,200,'restore initial layouts');
  assert.equal((await request(a,'/api/display','PUT',{...config,diagnosticsAutoOpenExcludedSlots:[1,17]})).status,200);
  assert.deepEqual((await request(a,'/api/config')).json.diagnosticsAutoOpenExcludedSlots,[1,17],'diagnostics exclusions persist');
  assert.equal((await request(a,'/api/display','PUT',{...config,preferredMonitor:1,preferredMonitorDevice:'\\\\.\\DISPLAY2',requestHardwareDecoding:false,showCameraStats:false})).status,200);
  const displaySaved=(await request(a,'/api/config')).json;
  assert.equal(displaySaved.preferredMonitorDevice,'\\\\.\\DISPLAY2','named display persists');
  assert.equal(displaySaved.requestHardwareDecoding,false,'global hardware decoding preference persists');
  assert.equal(displaySaved.showCameraStats,false,'Diagnostics statistics preference persists');
  const {requestHardwareDecoding: ignoredHardware, ...legacyDisplay}=displaySaved;
  assert.equal((await request(a,'/api/display','PUT',legacyDisplay)).status,200);
  assert.equal((await request(a,'/api/config')).json.requestHardwareDecoding,false,'legacy save preserves hardware preference');
  assert.equal((await request(a,'/api/display','PUT',config)).status,200);
  const addedStream=(await request(a,'/api/cameras','POST')).json;
  assert.equal((await request(a,'/api/cameras/'+addedStream.slot,'DELETE')).status,200,'stream deletes');
  const afterDeletion=(await request(a,'/api/config')).json;assert(afterDeletion.deletedCameraSlots.includes(addedStream.slot));
  assert.equal((await request(a,'/api/cameras/'+addedStream.slot,'DELETE')).status,400,'repeat deletion rejected');
  assert.equal((await request(a,'/api/cameras','POST')).json.slot,addedStream.slot,'deleted slot reused without renumbering');
  const automationLayouts=(await request(a,'/api/automation/layouts')).json.layouts;
  assert.equal(automationLayouts.length,2,'one and two focus templates provided');
  assert.equal(automationLayouts[1].focusSlots.length,2,'dual focus template has two positions');
  const editedLayouts=automationLayouts.map((l,i)=>({...l,name:i===1?'Edited dual focus':l.name}));
  assert.equal((await request(a,'/api/automation/layouts','PUT',{layouts:editedLayouts})).status,200,'automation layout saves');
  const layoutConfig=(await request(a,'/api/config')).json;
  assert.deepEqual(layoutConfig.layouts,config.layouts,'automation editor changed standard layouts');
  assert.equal(layoutConfig.activeLayoutId,config.activeLayoutId,'automation save changed live layout');
  assert.equal(layoutConfig.automationViewLayouts[1].name,'Edited dual focus','automation layout edit did not persist');
  assert.equal((await request(a,'/api/automation/layouts','PUT',{layouts:[{...editedLayouts[0],focusSlots:[1,1]}]})).status,400,'invalid focus positions rejected');
  const automation=(await request(a,'/api/automation')).json;
  assert.equal(automation.settings.enabled,false,'automation defaults off');
  const mqttSecret='test-mqtt-'+crypto.randomUUID();
  const savedAutomation=await request(a,'/api/automation','PUT',{settings:automation.settings,password:mqttSecret});
  assert.equal(savedAutomation.status,200);assert.equal(savedAutomation.json.hasPassword,true);
  assert(!savedAutomation.text.includes(mqttSecret),'saved secret is not returned');
  assert(!fs.readFileSync(path.join(data,'automation.json'),'utf8').includes(mqttSecret),'secret encrypted on disk');
  assert.equal((await request(a,'/api/automation','PUT',{settings:automation.settings,password:null})).json.hasPassword,true,'blank preserves password');
  assert.equal((await request(a,'/api/automation','PUT',{settings:automation.settings,clearPassword:true})).json.hasPassword,false,'explicit clear removes password');
  assert.equal((await request(a,'/api/automation/test','POST',{settings:automation.settings})).status,400,'test requires broker host');
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,host:null}})).status,400,'invalid connection is rejected');
  assert.equal((await request(a,'/api/automation/diagnostics')).json.connection,'Stopped','discovery starts stopped');
  assert.equal((await request(a,'/api/automation/diagnostics/start','POST',{connection:{settings:automation.settings}})).status,400,'discovery requires broker host');
  assert.equal((await request(a,'/api/automation/diagnostics/start','POST',{connection:{settings:{...automation.settings,host:'localhost'}},prefix:'#'})).status,400,'discovery rejects unrestricted wildcard prefix');
  a.csrf='';assert.equal((await request(a,'/api/automation/diagnostics/stop','POST',{})).status,400,'discovery stop requires CSRF');await session(a);
  const automaticOverlay={...config.doorbellOverlay,camera:{...config.doorbellOverlay.camera,enabled:false,rtspUrl:'rtsp://example.test/doorbell'}};
  assert.equal((await request(a,'/api/doorbell','PUT',automaticOverlay)).status,200,'automation-only overlay saves');
  assert.equal((await request(a,'/api/config')).json.doorbellOverlay.camera.enabled,false,'automation-only overlay stays hidden after reload');
  assert.equal((await request(a,'/api/cameras/'+automaticOverlay.hostCameraSlot,'DELETE')).status,400,'configured overlay host cannot be deleted');
  assert.equal((await request(a,'/api/doorbell','PUT',{...automaticOverlay,camera:{...automaticOverlay.camera,enabled:true}})).status,200,'always-visible overlay saves');
  assert.equal((await request(a,'/api/config')).json.doorbellOverlay.camera.enabled,true,'always-visible mode persists');
  await request(a,'/api/doorbell','PUT',config.doorbellOverlay);
  await request(a,'/api/cameras/1','PUT',{...config.cameras[0],enabled:true,rtspUrl:'rtsp://example.test/front'});
  const focusRule={id:crypto.randomUUID(),name:'Person focus',enabled:true,action:1,cameraSlot:0,overlaySlot:0,clearMinutes:2,sources:[{cameraSlot:1,topic:'scrypted/44/ObjectDetector'}]};
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,rules:[focusRule]}})).status,200,'fullscreen triggering-camera rule saves');
  assert.equal((await request(a,'/api/automation')).json.settings.rules[0].action,1,'fullscreen action persists');
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,rules:[{...focusRule,action:2,cameraSlot:1}]}})).status,200,'focused-layout fixed-camera rule saves');
  assert.equal((await request(a,'/api/automation')).json.settings.rules[0].cameraSlot,1,'fixed focus target persists');
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,rules:[{...focusRule,action:2,cameraSlot:1,layoutId:editedLayouts[1].id}]}})).status,200,'rule selects saved automation layout');
  assert.equal((await request(a,'/api/automation/layouts','PUT',{layouts:[editedLayouts[0]]})).status,400,'in-use automation layout cannot be deleted');
  await request(a,'/api/cameras/2','PUT',{...config.cameras[1],enabled:true,rtspUrl:'rtsp://example.test/second'});
  const paired={...focusRule,action:2,cameraSlot:1,secondCameraSlot:2,layoutId:editedLayouts[1].id};
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,rules:[paired]}})).status,200,'paired focus saves');
  assert.equal((await request(a,'/api/automation')).json.settings.rules[0].secondCameraSlot,2,'second camera persists');
  assert.equal((await request(a,'/api/cameras/2','DELETE')).status,400,'second focus camera deletion guarded');
  assert.equal((await request(a,'/api/automation/layouts','PUT',{layouts:[editedLayouts[0],{...editedLayouts[1],focusSlots:[editedLayouts[1].focusSlots[0]],tiles:editedLayouts[1].tiles.filter(t=>t.cameraSlot!==editedLayouts[1].focusSlots[1])}]})).status,400,'second focus position removal guarded');

  // Stable 1.0.44 permits incomplete targets in disabled automation drafts.
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,rules:[{...focusRule,action:2,cameraSlot:10}]}})).status,200,'disabled automation retains incomplete draft');
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,enabled:true,host:'localhost',rules:[{...focusRule,action:2,cameraSlot:10}]}})).status,400,'enabled focused layout rejects overlay target');
  await request(a,'/api/automation','PUT',{settings:automation.settings});
  await request(a,'/api/doorbell','PUT',automaticOverlay);
  const overlayRule={...focusRule,action:0,cameraSlot:0,overlaySlot:10};
  assert.equal((await request(a,'/api/automation','PUT',{settings:{...automation.settings,rules:[overlayRule]}})).status,200);
  assert.equal((await request(a,'/api/overlays/10','DELETE')).status,400,'rule prevents overlay deletion');
  await request(a,'/api/automation','PUT',{settings:automation.settings});
  a.csrf='';assert.equal((await request(a,'/api/overlays/10','DELETE')).status,400,'overlay deletion requires CSRF');await session(a);
  assert.equal((await request(a,'/api/overlays/10','DELETE')).status,200,'built-in overlay can be deleted');
  assert.equal((await request(a,'/api/config')).json.doorbellOverlay.camera.rtspUrl,'','overlay credentials cleared');
  assert((await request(a,'/api/config')).json.deletedOverlaySlots.includes(10),'overlay deletion persists');
  assert.equal((await request(a,'/api/overlays','POST')).json.camera.slot,10,'deleted built-in overlay slot reused');
  const extra=(await request(a,'/api/overlays','POST')).json;
  assert.equal((await request(a,'/api/overlays/'+extra.camera.slot,'DELETE')).status,200,'additional overlay can be deleted');
  assert.equal((await request(a,'/api/overlays','POST')).json.camera.slot,extra.camera.slot,'additional overlay slot reused');
  await request(a,'/api/cameras/1','PUT',config.cameras[0]);await request(a,'/api/cameras/2','PUT',config.cameras[1]);
  assert.equal((await request(a,'/api/dependencies/pawnio/install','POST',{confirmed:false})).status,400,'dependency install requires confirmation');
  assert.equal((await request(a,'/api/dependencies/pawnio/arbitrary','POST',{confirmed:true})).status,404,'arbitrary maintenance actions rejected');
  assert.equal((await request(a,'/api/dependencies/pawnio/install','POST',{confirmed:true})).status,409,'test environment cannot install host dependencies');
  a.csrf='';assert.equal((await request(a,'/api/dependencies/pawnio/enable-helper','POST',{confirmed:true})).status,400,'helper setup requires CSRF');await session(a);
  const thermal=(await request(a,'/api/temperatures')).json;
  assert.equal(thermal.settings.showWarnings,false,'all temperature warnings initially off');
  const thermalSettings={...thermal.settings,showWarnings:true,cpuWarningEnabled:true,gpuWarningEnabled:true,cpuMaxC:82,gpuMaxC:77};
  assert.equal((await request(a,'/api/temperatures','PUT',thermalSettings)).status,200);
  assert.equal((await request(a,'/api/temperatures')).json.settings.gpuMaxC,77,'temperature limits saved');
  assert.equal((await request(a,'/api/temperatures','PUT',{...thermalSettings,cpuMaxC:200})).status,400,'invalid temperature limit rejected');
  a.csrf='';assert.equal((await request(a,'/api/temperatures','PUT',thermalSettings)).status,400,'temperature CSRF required');await session(a);
  assert.equal((await request(a,'/api/temperatures','PUT',{...thermalSettings,showWarnings:false})).status,200,'master warning off');
  assert.equal((await request(a,'/api/update')).json.showWallNotifications,true,'wall notices enabled by default');
  assert.equal((await request(a,'/api/update/notifications','PUT',{enabled:false})).status,200);
  assert.equal((await request(a,'/api/update')).json.showWallNotifications,false,'notification toggle saved');
  a.csrf='';assert.equal((await request(a,'/api/update/notifications','PUT',{enabled:true})).status,400,'notification CSRF required');
  assert.equal((await request(a,'/api/update/check','POST')).status,400,'manual update check CSRF required');await session(a);
  for(const camera of [config.camera,...config.cameras,config.doorbellOverlay.camera,config.garageOverlay.camera,...config.additionalOverlays.map(o=>o.camera)])assert.equal(camera.rtspUrl,'','fresh camera URL empty');
  assert.equal(config.snapshots.enabled,false,'snapshot schedule off by default');
  const schedule=(await request(a,'/api/restart-schedule')).json;
  assert.equal(schedule.schedule.settings.enabled,false,'restart schedule off by default');
  assert(schedule.timeZoneId,'host timezone supplied');
  const restartSettings={enabled:true,action:'host',mode:'interval',intervalHours:24,days:[0],time:'03:00'};
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:restartSettings})).status,400,'host reboot acknowledgement required');
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:{...restartSettings,intervalHours:0},hostAcknowledged:true})).status,400,'invalid schedule rejected');
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:restartSettings,hostAcknowledged:true})).status,200);
  const beforeSkip=(await request(a,'/api/restart-schedule')).json.schedule;
  assert.equal(beforeSkip.settings.action,'host','schedule persisted');
  assert.equal((await request(a,'/api/restart-schedule/skip','POST')).status,200);
  assert(new Date((await request(a,'/api/restart-schedule')).json.schedule.nextRun)>new Date(beforeSkip.nextRun),'skip advances schedule');
  a.csrf='';
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:restartSettings,hostAcknowledged:true})).status,400,'schedule CSRF required');
  assert.equal((await request(a,'/api/restart-schedule/skip','POST')).status,400,'skip CSRF required');await session(a);
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:{...restartSettings,enabled:false}})).status,200,'disable needs no reboot acknowledgement');
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:{...restartSettings,action:'viewer',intervalHours:2}})).status,200);
  assert.equal((await request(a,'/api/restart-schedule','PUT',{settings:restartSettings,hostAcknowledged:true})).status,200);
  const both=(await request(a,'/api/restart-schedule')).json.schedules;
  assert(both.viewer.settings.enabled && both.host.settings.enabled,'both schedules enabled independently');
  assert.equal(both.viewer.settings.intervalHours,2,'host save preserves viewer settings');
  assert.equal((await request(a,'/api/restart-schedule/skip?action=viewer','POST')).status,200);
  const skippedViewer=(await request(a,'/api/restart-schedule')).json.schedules;
  assert.equal(skippedViewer.host.nextRun,both.host.nextRun,'targeted skip preserves other schedule');
  assert(new Date(skippedViewer.viewer.nextRun)>new Date(both.viewer.nextRun),'targeted viewer skip advances viewer');
  assert.equal((await request(a,'/api/restart-schedule/skip?action=invalid','POST')).status,400,'unknown action rejected');
  a.csrf='';assert.equal((await request(a,'/api/restart-schedule/skip?action=host','POST')).status,400,'targeted skip CSRF required');await session(a);
  assert.equal((await request(a,'/api/snapshots/settings','PUT',{enabled:true,intervalHours:0})).status,400,'invalid interval rejected');
  assert.equal((await request(a,'/api/snapshots/settings','PUT',{enabled:true,intervalHours:0.5})).status,200);
  assert.equal((await request(a,'/api/config')).json.snapshots.intervalHours,0.5,'snapshot settings persisted');
  a.csrf='';assert.equal((await request(a,'/api/snapshots/settings','PUT',{enabled:false,intervalHours:1})).status,400,'snapshot CSRF required');await session(a);
  const revisionConfig=(await request(a,'/api/config')).json;
  const draft={layouts:revisionConfig.layouts.map(l=>({...l,name:l.name+' revised'})),activeLayoutId:revisionConfig.activeLayoutId,revision:revisionConfig.layoutRevision};
  const applied=await request(a,'/api/layouts','PUT',draft);assert.equal(applied.status,200);assert.notEqual(applied.json.revision,draft.revision);
  assert.equal((await request(a,'/api/layouts','PUT',draft)).status,409,'stale layout rejected');
  const autoDraft={layouts:revisionConfig.automationViewLayouts.map(l=>({...l,name:l.name+' revised'})),revision:revisionConfig.automationLayoutRevision};
  assert.equal((await request(a,'/api/automation/layouts','PUT',autoDraft)).status,200);
  assert.equal((await request(a,'/api/automation/layouts','PUT',autoDraft)).status,409,'stale automation layout rejected');
  const state=fs.readFileSync(path.join(data,'web-security.json'),'utf8');assert(!state.includes(password));assert(!state.includes('admin'));assert.equal(JSON.parse(state).PasswordChangeRequired,false);assert(!fs.existsSync(path.join(data,'initial-admin-password.txt')));
  const url='rtsp://test-user:test-pass@camera.example/live?token=test-query';const camera={...config.cameras[0],rtspUrl:url};assert.equal((await request(a,'/api/cameras/1','PUT',camera)).status,200);
  const exported=await request(a,'/api/config/export');assert(!exported.text.includes('test-pass'));assert(!exported.text.includes('test-query'));
  a.csrf='';assert.equal((await request(a,'/api/display','PUT',{})).status,400,'CSRF required');await session(a);
  const logs=fs.readdirSync(path.join(data,'logs')).map(p=>fs.readFileSync(path.join(data,'logs',p),'utf8')).join('');assert(!logs.includes(password));assert(!logs.includes('test-pass'));assert(!logs.includes('test-query'));
  for(let i=0;i<5;i++)await request(b,'/api/auth/login','POST',{password:'wrong'});assert.equal((await request(b,'/api/auth/login','POST',{password:'wrong'})).status,429);
  console.log('Admin security checks passed: all protected routes, setup gate, blank URLs, password rotation, session invalidation, CSRF, sanitized export/logs and throttling.');
 }finally{child.kill();await new Promise(resolve=>{if(child.exitCode!==null)resolve();else child.once('exit',resolve)});}
})().catch(error=>{console.error('Admin security checks FAILED: '+error.message);process.exitCode=1});
