// Disposable UI fixture: serves shipped assets with in-memory API responses.
// Never starts the viewer, changes host settings, or contacts cameras.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../src/RTSPView.Controller/wwwroot');
const names=['Front entrance','Driveway','Back garden','Side gate','Patio','Workshop','North fence','Parking','Office'];
const camera=(slot,name)=>({slot,name,enabled:true,rtspUrl:'rtsp://camera.example/stream',transport:1,networkCacheMilliseconds:1000,startupTimeoutSeconds:20,watchdogTimeoutSeconds:15,maximumReconnectBackoffSeconds:60,compositeStream:false,lowLatency:false,decodeAudio:false});
const overlay=(slot,name,host)=>({camera:camera(slot,name),hostCameraSlot:host,viewportWidthPercent:40,viewportHeightPercent:40,viewportHorizontalPositionPercent:0,viewportVerticalPositionPercent:100,viewportOpacityPercent:100,viewportShape:0,customViewportSourceName:'',customViewportPathData:'',customViewportViewBoxX:0,customViewportViewBoxY:0,customViewportViewBoxWidth:1,customViewportViewBoxHeight:1,customViewportRotationDegrees:0,zoomPercent:100,imageHorizontalPositionPercent:50,imageVerticalPositionPercent:50});
const config={cameras:names.map((name,i)=>camera(i+1,name)),cameraCount:9,doorbellOverlay:overlay(10,'Doorbell',1),garageOverlay:overlay(11,'Garage',3),additionalOverlays:[],startFullScreen:true,preferredMonitor:0,preferredMonitorDevice:"fixture-display-1",requestHardwareDecoding:true,hideMouseCursor:true,mouseCursorHideSeconds:3,showCameraNames:false,showCameraStats:false,keepViewerAlwaysOnTop:true,activeLayoutId:'default',layouts:[{id:'default',name:'Main wall',rows:3,columns:3,aspectRatio:'16:9',tiles:names.map((_,i)=>({cameraSlot:i+1,row:Math.floor(i/3),column:i%3,rowSpan:1,columnSpan:1}))}]};
let schedule={settings:{enabled:false,action:'viewer',mode:'weekly',intervalHours:24,days:[0],time:'03:00'},nextRun:null,pendingUntil:null,lastRun:null,result:'No scheduled restarts yet.'}; const schedules={viewer:schedule,host:{...schedule,settings:{...schedule.settings,action:'host',days:[0]}}}; const scheduleStatus=()=>({schedule,schedules,timeZone:'Pacific Time',timeZoneId:'America/Los_Angeles',serverTime:new Date().toISOString()});
let temperatureSettings={showWarnings:false,cpuWarningEnabled:false,gpuWarningEnabled:false,cpuMaxC:90,gpuMaxC:85}; const temperatureStatus=()=>({settings:temperatureSettings,timestamp:new Date().toISOString(),cpuC:62.5,gpuC:58.2});
config.automationViewLayouts=[{...config.layouts[0],id:'automation-default',name:'Focused wall',focusSlots:[-1],tiles:config.layouts[0].tiles.map((t,i)=>i===0?{...t,cameraSlot:-1}:t)},{...config.layouts[0],id:'automation-dual',name:'Two focus cameras',focusSlots:[-1,-2],tiles:config.layouts[0].tiles.map((t,i)=>i<2?{...t,cameraSlot:-i-1}:t)}];
let viewerRunning=true, viewerFullScreen=false;
let wallNotifications=true;let channel='beta';
const update=()=>({showWallNotifications:wallNotifications,lastChecked:new Date().toISOString(),nextCheck:new Date(Date.now()+86400000).toISOString(),installedVersion:'1.0.40-beta.1',installedChannel:'beta',selectedChannel:channel,latestVersion:channel==='beta'?'1.0.40-beta.1':'1.0.39',channelAvailable:true,updateAvailable:channel!=='beta',message:channel==='beta'?'RTSPView is up to date on this channel.':'RTSPView 1.0.39 is ready to install.'});
const network={enabled:true,managed:true,message:'LAN access enabled on private networks.',addresses:['http://192.0.2.10:5080','http://192.0.2.11:5080']};
let automation={settings:{enabled:false,host:"",port:1883,tls:false,authenticate:false,username:"",clientId:"rtspview-fixture",rules:[]},hasPassword:false};
let diagnosticRunning=false;
let tapo={settings:{enabled:false,username:'',pollSeconds:5,hubs:[],rules:[]},hasPassword:false};
const tapoSnapshot=hubs=>({hubs:hubs.map((h,i)=>({id:h.id,name:h.name,model:i?'H200':'H100',connected:true,message:'Connected · fixture only'})),sensors:hubs.map((h,i)=>({hubId:h.id,deviceId:'fixture-door-'+i,name:i?'Back door':'Garage door',model:'T110',state:i?1:2}))});
const diagnostics=()=>({connection:diagnosticRunning?'Listening':'Stopped',until:diagnosticRunning?new Date(Date.now()+300000).toISOString():null,topics:diagnosticRunning?[{topic:'scrypted/44/ObjectDetector',cameraName:config.cameras[0].name,lastSeen:new Date().toISOString(),personSeen:true},{topic:'scrypted/45/ObjectDetector',cameraName:config.cameras[1].name,lastSeen:new Date().toISOString(),personSeen:false}]:[],messages:diagnosticRunning?[{id:1,received:new Date().toISOString(),topic:'scrypted/44/ObjectDetector',payload:JSON.stringify({timestamp:Date.now(),detections:[{className:'person',score:0.92}]}),retained:false,qos:0,truncated:false},{id:2,received:new Date().toISOString(),topic:'scrypted/44/motionDetected',payload:'true',retained:true,qos:0,truncated:false}]:[]});
const mutations=[];
http.createServer(async(req,res)=>{
 const url=new URL(req.url,'http://127.0.0.1'),route=url.pathname;
 const json=value=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value))};
 if(route==='/api/weather')return json([]);
 if(route==='/api/weather/search')return json({results:[{name:'Seattle',admin1:'Washington',country:'United States',latitude:47.6062,longitude:-122.3321,timezone:'America/Los_Angeles'}]});
 if(route.startsWith('/api/weather/overlays/')){let body='';for await(const chunk of req)body+=chunk;const o=JSON.parse(body);config.weatherOverlays=[...(config.weatherOverlays||[]).filter(w=>w.hostCameraSlot!==o.hostCameraSlot),o];return json(o);}

 if(route==='/api/automation/priorities'){
  const snapshot=()=>({revision:'fixture',rules:[...automation.settings.rules.map(r=>({...r,source:'MQTT'})),...tapo.settings.rules.map(r=>({...r,source:'Tapo'}))].sort((a,b)=>a.priority-b.priority)});
  if(req.method==='GET')return json(snapshot());
  let body='';for await(const chunk of req)body+=chunk;JSON.parse(body).rules.forEach((r,i)=>{const settings=r.source==='MQTT'?automation.settings:tapo.settings;settings.rules.find(n=>n.id===r.id).priority=i+1});return json(snapshot());
 }
 if(route==='/api/automation/layouts'){
  if(req.method==='GET')return json({layouts:config.automationViewLayouts,activeLayoutId:config.automationViewLayouts[0].id});
  let body='';for await(const chunk of req)body+=chunk;const r=JSON.parse(body);config.automationViewLayouts=r.layouts;return json(r);
 }
 if(route==='/api/tapo/account'&&req.method==='DELETE'){tapo={settings:{...tapo.settings,enabled:false,username:''},hasPassword:false};return json(tapo)}
 if(route.startsWith('/api/tapo')){
  let body='';for await(const chunk of req)body+=chunk;
  if(route==='/api/tapo'&&req.method==='GET')return json(tapo);
  if(route==='/api/tapo/discover-hubs')return json({hubs:[],sensors:[],discoveredHubs:[{id:'a0000000-0000-4000-8000-000000000001',name:'Preview H100',host:'192.0.2.10'},{id:'a0000000-0000-4000-8000-000000000002',name:'Preview H200',host:'192.0.2.11'}]});
  if(route==='/api/tapo/status')return json({connection:tapo.settings.enabled?'Connected':'Disabled',message:'Synthetic Tapo preview',lastChecked:new Date().toISOString(),...tapoSnapshot(tapo.settings.hubs),activeRules:[],testingRules:[]});
  if(route==='/api/tapo/discover')return json(tapoSnapshot(JSON.parse(body).settings.hubs));
  if(route.endsWith('/test'))return json({success:true,message:'Fixture test recorded.'});
  if(route==='/api/tapo'&&req.method==='PUT'){const r=JSON.parse(body);tapo={settings:r.settings,hasPassword:r.clearPassword?false:!!r.password||tapo.hasPassword};return json(tapo)}
 }
 if(route==='/api/onvif/discover')return json({devices:[{name:'Fixture camera',address:'http://192.0.2.20/onvif/device_service'}]});
 if(route==='/api/onvif/profiles')return json({profiles:[{token:'main',name:'Main stream',encoding:'H264',width:1920,height:1080,mediaVersion:1},{token:'sub',name:'Substream',encoding:'H264',width:640,height:360,mediaVersion:1}]});
 if(route==='/api/onvif/stream')return json({rtspUrl:'rtsp://192.0.2.20/substream'});
 if(route==='/api/cameras' && req.method==='POST'){const camera={...config.cameras[0],slot:26+config.cameras.filter(c=>c.slot>=26).length,name:'New stream',rtspUrl:'',enabled:true};config.cameras.push(camera);config.cameraCount=config.cameras.length;return json(camera)}
 if(route.startsWith('/api/control/viewer/')){const action=route.split('/').pop();if(action==='start')viewerRunning=true;if(action==='enter-fullscreen')viewerFullScreen=true;if(action==='exit-fullscreen')viewerFullScreen=false;return json({message:'Fixture command completed.'})}
 if(req.method!=='GET'){let body='';for await(const chunk of req)body+=chunk;mutations.push({route,method:req.method,body});console.log(req.method,route,body);if(route==='/api/automation/diagnostics/start'){diagnosticRunning=true;return json(diagnostics())}if(route==='/api/automation/diagnostics/stop'){diagnosticRunning=false;return json(diagnostics())}if(route==='/api/automation/test')return json({success:true,message:'Fixture connection accepted; no actions enabled.'});if(route==='/api/automation'){const request=JSON.parse(body);automation={settings:request.settings,hasPassword:request.clearPassword?false:!!request.password||automation.hasPassword};return json(automation)}if(route==='/fixture/restart-countdown'){schedule=schedules.host;schedule.settings.enabled=true;schedule.settings.action='host';schedule.pendingUntil=new Date(Date.now()+60000).toISOString();schedule.nextRun=new Date().toISOString();schedule.result='Windows host restart in 60 seconds. Cancel to skip this run.';return json(scheduleStatus())}if(route==='/api/restart-schedule'){schedule=schedules[JSON.parse(body).settings.action];schedule.settings=JSON.parse(body).settings;schedule.nextRun=schedule.settings.enabled?new Date(Date.now()+86400000).toISOString():null; schedule.result='Schedule saved.';return json(scheduleStatus())}if(route==='/api/restart-schedule/skip'){schedule=schedules[url.searchParams.get('action')||schedule.settings.action];schedule.pendingUntil=null;schedule.nextRun=new Date(Date.now()+172800000).toISOString();schedule.result='Scheduled restart skipped by administrator.';return json(scheduleStatus())}if(route==='/api/snapshots/settings'){config.snapshots=JSON.parse(body);return json(config.snapshots)}if(route==='/api/cameras/6/thumbnail/refresh'){res.statusCode=503;return json({error:'Fixture stream unavailable'})}if(route==='/api/temperatures'){temperatureSettings=JSON.parse(body);return json(temperatureStatus())}if(route==='/api/update/check')return json(update());if(route==='/api/update/notifications'){wallNotifications=JSON.parse(body).enabled;return json(update())}if(route==='/api/update/channel'){channel=JSON.parse(body).channel;return json(update())}if(route==='/api/display'){Object.assign(config,JSON.parse(body));return json(config)}if(route==='/api/network')Object.assign(network,JSON.parse(body));if(route==='/api/layouts'){Object.assign(config,JSON.parse(body));return json(JSON.parse(body))}if(route==='/api/doorbell'){config.doorbellOverlay=JSON.parse(body);return json(config.doorbellOverlay)}if(route==='/api/garage'){config.garageOverlay=JSON.parse(body);return json(config.garageOverlay)}if(/^\/api\/cameras\/\d+$/.test(route)){const camera=JSON.parse(body);const index=config.cameras.findIndex(c=>c.slot===camera.slot);if(index>=0)config.cameras[index]=camera;return json(camera);}return json({message:'Fixture action recorded.'})}
 if(route==='/fixture/mutations')return json(mutations);
 if(route==='/api/session')return json({authenticated:true,passwordChangeRequired:false,csrfToken:'fixture-only'});
 if(route==='/api/status')return json({hostname:'RTSPVIEW-DEMO',lanAddresses:['192.0.2.10'],version:'1.0.40-beta.1',currentTime:'2026-09-12T22:15:00Z'});
 if(route==='/api/temperatures')return json(temperatureStatus());
 if(route==='/api/restart-schedule')return json(scheduleStatus());
 if(route==='/api/config')return json(config);
 if(route==='/api/automation/diagnostics')return json(diagnostics());
 if(route==='/api/automation')return json(automation);
 if(route==='/api/automation/presentation')return json({presentation:{at:new Date().toISOString(),rules:[]}});
 if(route==='/api/automation/status')return json({connection:automation.settings.enabled?'Connected':'Disabled',lastResult:'Fixture only',lastMessage:null,lastPerson:null,rules:automation.settings.rules});
 if(route==='/api/update')return json(update());
 if(route==='/api/network')return json(network);
 if(route==='/api/logs')return json({lines:['[Info] Viewer connected.','[Info] Camera streams initialized.']});
 if(route==='/api/telemetry')return json({viewerConnected:viewerRunning,viewerRunning,viewerStarting:false,viewerPaused:false,system:{cpuPercent:12,ramUsedGb:5.4,ramTotalGb:16,cpuTemperatureC:62.5,gpuTemperatureC:58.2,gpuPercent:8,gpuVideoDecodePercent:18,networkReceiveMbps:24,networkSendMbps:1},viewer:{displays:[{index:0,deviceName:"fixture-display-1",label:"Display 1 — Main wall — 1920 × 1080 — Primary",primary:true,width:1920,height:1080},{index:1,deviceName:"fixture-display-2",label:"Display 2 — Portrait wall — 1080 × 1920",primary:false,width:1080,height:1920}],isFullScreen:viewerFullScreen,viewerMemoryMb:480,cameras:[...config.cameras,config.doorbellOverlay.camera,config.garageOverlay.camera].map((c,i)=>({...c,state:i===4?'Reconnecting':i===5?'StreamError':i===8?'Disabled':'Live',fps:15,width:1280,height:720,codec:'H264',bitrateKbps:246,reconnectCount:i===4?2:0,decoder:'Hardware active (D3D11VA)',frameWarning:i===4?'Last frame received 23 seconds ago':null,lastError:i===5?'Decoder unavailable. Retrying the stream connection.':null}))}});
 if(route.endsWith('/thumbnail')){res.setHeader('Content-Type','image/svg+xml');return res.end('<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#243139"/><path d="M0 340L280 180L600 370L980 160L1280 330V720H0Z" fill="#364b43"/><path d="M200 720L640 390L920 720" fill="#7b8280"/><rect x="650" y="230" width="360" height="230" fill="#9b968a"/><path d="M600 240L830 100L1060 240" fill="#3d4751"/><rect x="720" y="280" width="80" height="180" fill="#3f5158"/><text x="35" y="680" fill="#e4e9e7" font-family="sans-serif" font-size="24">UI preview · synthetic camera image</text></svg>')}
 const file=path.resolve(root,'.'+(route==='/'?'/index.html':route));
 if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end('Not found')}
 res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.ico':'image/x-icon'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);
}).listen(Number(process.env.PREVIEW_PORT||5099),process.env.PREVIEW_HOST||'127.0.0.1',()=>console.log('UI fixture ready'));
