<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><RuntimeIdentifier>win-x64</RuntimeIdentifier></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/RTSPView.Maintenance/RTSPView.Maintenance.csproj" /></ItemGroup>
</Project>
