<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <ProjectReference Include="..\RTSPView.Core\RTSPView.Core.csproj" />
  </ItemGroup>
</Project>
